'use strict';

// PR-F — structural wiring guards for the plan-acceptance path and its app.js
// bridge, read against the built shell (public/, regenerated by pretest).
// Complements the behavioral unit tests (planAcceptance.test.js / …Persistence).
// The plan-card "Start this plan" button was retired in the composer-chat
// simplification (owner); acceptance now fires automatically when the first set is
// logged (the app.js gate). These pins hold that the ONE acceptance adapter
// (acceptDisplayedPlan) still delegates to the orchestrator, posts ONLY /accept
// (no outcome/closeout in PR-F), never touches the main workout-write path, and
// leaves the generic "Start Session" control unchanged.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const publicDir = path.join(__dirname, '..', 'public');
const app = fs.readFileSync(path.join(publicDir, 'app.js'), 'utf8');
const cc = fs.readFileSync(path.join(publicDir, 'coach-conversation.js'), 'utf8');
const sw = fs.readFileSync(path.join(publicDir, 'sw.js'), 'utf8');

// The acceptDisplayedPlan function body (adapter) — sliced for scoped assertions.
const acceptBlock = app.slice(app.indexOf('async function acceptDisplayedPlan('), app.indexOf('function emitPlanItemOutcome('));

test('the plan-card "Start this plan" button is retired — the plan card is display-only', () => {
  assert.doesNotMatch(cc, /function appendStartThisPlanButton\(/, 'the plan-card accept button helper is gone');
  assert.doesNotMatch(cc, /start-this-plan-btn/, 'no "Start this plan" button is rendered anywhere');
  assert.doesNotMatch(cc, /appendStartThisPlanButton\(/, 'the plan card no longer appends an accept button');
  // Rendering the plan card is display-only; the acceptance adapter is never called
  // from the coach conversation layer.
  assert.doesNotMatch(cc, /atlasAcceptPlan\(/, 'the coach conversation never triggers acceptance directly');
});

test('acceptance runs automatically at the app.js log gate via the ONE acceptance adapter', () => {
  // Merely rendering the Coach's Pick is not acceptance; logging the first set from
  // an unaccepted displayed plan silently accepts it through the same adapter.
  assert.match(app, /const gateRec = unacceptedPlanGateRec\(logRows\);/, 'the mid-session log gate exists');
  const gateBlock = app.slice(app.indexOf('const gateRec = unacceptedPlanGateRec(logRows);'),
    app.indexOf('Substitution classification:', app.indexOf('const gateRec = unacceptedPlanGateRec(logRows);')));
  assert.match(gateBlock, /acceptDisplayedPlan\(gateRec\)/, 'the gate accepts the displayed plan on a logged set');
  assert.match(gateBlock, /atlasResumeBlockedLog/, 'the held set resumes after acceptance');
});

test('the Coach\'s Pick fetch syncs the displayed plan into the gate\'s source (no stale/absent cache)', () => {
  // The retired button carried the exact displayed rec; the gate instead reads the
  // displayed plan from lastIntentData. The coach fetch — which does not go through
  // loadDashboard — keeps that source aligned with the pick it renders, so logging
  // accepts the DISPLAYED plan and never skips acceptance on an empty dashboard cache.
  assert.match(app, /window\.atlasSyncDisplayedIntent = \(intentData\) =>/, 'app.js exposes the displayed-intent sync');
  assert.match(app, /lastIntentData = intentData;/, 'the sync refreshes lastIntentData (the gate source)');
  assert.match(cc, /window\.atlasSyncDisplayedIntent\(data\)/, 'the Coach\'s Pick fetch syncs its displayed plan into the gate source');
  // The fetch now appends buildIntentRecommendationQuery(constraints) (workout-generation
  // routing, 2026-07-22), so match the endpoint prefix rather than the exact call.
  const fetchIdx = cc.indexOf("api('/api/plan/intent-recommendation'");
  const syncIdx = cc.indexOf('window.atlasSyncDisplayedIntent(data)');
  assert.ok(fetchIdx !== -1 && syncIdx > fetchIdx, 'the sync follows the coach intent fetch');
});

test('acceptDisplayedPlan is bridged and delegates to the pure orchestrator', () => {
  assert.match(app, /window\.atlasAcceptPlan = acceptDisplayedPlan;/, 'the adapter is bridged for the coach IIFE');
  assert.match(app, /import \{ runAcceptance \} from '\.\/planAcceptance\.js';/, 'app.js imports the pure orchestrator');
  assert.match(acceptBlock, /runAcceptance\(/, 'the adapter delegates to runAcceptance');
});

test('acceptance posts ONLY /api/session-plans/accept — no outcome or closeout in PR-F', () => {
  assert.match(acceptBlock, /\/api\/session-plans\/accept/, 'the adapter posts to the accept endpoint');
  // The ACCEPTANCE flow itself emits only /accept — never an outcome or closeout.
  // (PR-G1 adds /outcome elsewhere in app.js at the explicit skip/substitute handlers;
  // closeout stays unwired until PR-H.)
  assert.doesNotMatch(acceptBlock, /\/api\/session-plans\/outcome/, 'the accept flow does not send an outcome');
  assert.doesNotMatch(acceptBlock, /\/api\/session-plans\/closeout/, 'the accept flow does not send a closeout');
});

test('the adapter never derives a session identity — server-allocated, client-adopted (authority fix 2026-08-03)', () => {
  // The removed authority stays removed: acceptDisplayedPlan's hardcoded
  // `${date}-{AM|PM}-01` mint re-used the first same-period session's identity,
  // writing a second accepted plan into a finalized, sealed workout
  // (docs/verification/ACCEPTED_PLAN_IDENTITY_2026-08-03.md). Identity is either
  // already ESTABLISHED (#log-session-id) or the SERVER allocates it at /accept
  // and the adapter adopts the response's identity.
  assert.doesNotMatch(acceptBlock, /generateSessionId\(/, 'the acceptance adapter never mints a session identity');
  assert.match(acceptBlock, /sessionId: existingId \|\| null,/, 'no established identity → null, never a derived id');
  assert.match(acceptBlock, /adoptSessionId: \(sid\) => \{/, 'the adapter wires the server-identity adoption hook');
  assert.match(acceptBlock, /sessionIdEl\.value = sid;/, 'adoption stamps the field the save/closeout flows read');
});

test('acceptance never touches the main workout-write / trust path', () => {
  assert.doesNotMatch(acceptBlock, /\/api\/log-workout|\/api\/complete-workout|sheet_write|no_write_confirmed|beginWrite/,
    'the acceptance adapter must not touch the workout write/proof path (sidecar only)');
});

test('the generic "Start Session" control is unchanged (still non-authoritative)', () => {
  // #start-session-btn still only opens the Coach\'s Pick surface — it is NOT wired to
  // acceptance (owner test 19). The distinct plan-card button owns acceptance.
  // Wrapped in an arrow so the click Event is never passed as generation constraints
  // (2026-07-22) — still just opens the pick, never acceptance.
  assert.match(app, /btn\.onclick = \(\) => openCoachPickInThread\(\);/, 'the generic Start Session button still just opens the coach surface');
  assert.doesNotMatch(app, /start-session-btn[\s\S]{0,200}atlasAcceptPlan/, 'the generic control is not repurposed for acceptance');
});

test('acceptance clears any stale pending swap (new-session boundary, parity with startPlannedSession)', () => {
  assert.match(acceptBlock, /setPendingSubstitution\(null\)/,
    'a newly-accepted session must not inherit a stale swap');
});

test('a deload pick still keeps its own owner-gated flow — never auto-accepted at the gate', () => {
  // The button used to suppress deload; the same protection now lives in the app.js
  // gate, which returns null for a deload pick so it is never auto-accepted.
  const gateFn = app.slice(app.indexOf('function unacceptedPlanGateRec('), app.indexOf('function unacceptedPlanGateRec(') + 1400);
  assert.match(gateFn, /rec\.id === 'deload_reset'\) return null;/, 'the gate excludes a deload pick from auto-acceptance');
});

test('the new module is precached and the shell cache is bumped', () => {
  assert.match(sw, /\/app\/planAcceptance\.js/, 'planAcceptance.js is in SHELL_ASSETS (offline-safe)');
  assert.match(sw, /atlas-shell-v146/, 'the SW cache version is bumped for the new asset');
});
