'use strict';

// PR-G1 — structural wiring guards for explicit skipped/substituted outcome capture,
// read against the built shell (public/, regenerated by pretest). Complements the
// pure unit tests (planOutcome.test.js): pins that the explicit skip/substitution
// handlers emit outcomes carrying the immutable plan_item_id (captured off the slot),
// that substitution keeps the original identity, that emission is a non-blocking
// sidecar POST to /outcome only (no completed, no closeout this slice), and that
// identity is never recovered by lift-code/name.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const publicDir = path.join(__dirname, '..', 'public');
const app = fs.readFileSync(path.join(publicDir, 'app.js'), 'utf8');
const outcome = fs.readFileSync(path.join(publicDir, 'planOutcome.js'), 'utf8');
const sw = fs.readFileSync(path.join(publicDir, 'sw.js'), 'utf8');

const skipBlock = app.slice(app.indexOf('function skipPlannedExercise('), app.indexOf('function announcePlanMutation('));
const subBlock = app.slice(app.indexOf('function applySessionSubstitution('), app.indexOf('function startPlannedSession('));
const emitBlock = app.slice(app.indexOf('function emitPlanItemOutcome('), app.indexOf('function emitPlanItemOutcome(') + 800);

test('app.js imports the pure outcome orchestrator', () => {
  assert.match(app, /import \{ runOutcome \} from '\.\/planOutcome\.js';/);
});

test('skip captures the plan_item_id off the slot BEFORE splicing, then emits a skipped outcome', () => {
  assert.match(skipBlock, /const removedItemId = getActivePlannedSession\(\)\.exercises\[idx\]\.plan_item_id;/,
    'identity is read off the slot before the splice destroys position');
  // the capture precedes the splice
  assert.ok(skipBlock.indexOf('removedItemId') < skipBlock.indexOf('.splice('), 'id captured before splice');
  assert.match(skipBlock, /emitPlanItemOutcome\(\{ plan_item_id: removedItemId, outcome: 'skipped' \}\)/);
});

test('substitution keeps the original plan_item_id on the slot and emits a substituted outcome with the performed code', () => {
  assert.match(subBlock, /const originalItemId = exs\[idx\]\.plan_item_id;/, 'original identity captured before replace/splice');
  assert.match(subBlock, /plan_item_id: originalItemId/, 'the replacement slot RETAINS the original identity');
  assert.match(subBlock, /emitPlanItemOutcome\(\{ plan_item_id: originalItemId, outcome: 'substituted', performed_lift_code: subLiftCode \}\)/,
    'substituted keeps the original item id and records the performed code');
});

test('outcome emission is a non-blocking sidecar POST to /outcome, gated on an accepted plan', () => {
  assert.match(emitBlock, /plan\.accepted !== true\) return;/, 'only accepted plans emit outcomes');
  assert.match(emitBlock, /\/api\/session-plans\/outcome/, 'posts to the outcome endpoint');
  assert.match(emitBlock, /runOutcome\(/, 'delegates to the pure orchestrator');
  assert.match(emitBlock, /\.catch\(/, 'fire-and-forget — never blocks the workout');
});

test('identity is resolved by plan_item_id only — never lift-code / name / position', () => {
  const resolve = outcome.slice(outcome.indexOf('export function resolveItemForOutcome('), outcome.indexOf('export function resolveItemForOutcome(') + 400);
  assert.match(resolve, /_str\(it\.plan_item_id\) === id/, 'match is by plan_item_id');
  assert.doesNotMatch(resolve, /planned_lift_code|\.name|\.liftCode/, 'no lift-code/name fallback in identity resolution');
});

test('PR-G1 scope: the skip/substitute outcome handlers emit neither completed nor closeout', () => {
  // The two outcome handlers use skipped/substituted only (completed is PR-G2, on a
  // different handler; closeout is PR-H, on the explicit close/discard affordances).
  assert.doesNotMatch(skipBlock + subBlock, /outcome: 'completed'/, 'skip/substitute never emit completed');
  assert.doesNotMatch(skipBlock + subBlock, /\/api\/session-plans\/closeout/, 'skip/substitute never emit closeout');
});

test('the new module is precached and the shell cache is bumped', () => {
  assert.match(sw, /\/app\/planOutcome\.js/, 'planOutcome.js is in SHELL_ASSETS');
  assert.match(sw, /atlas-shell-v141/, 'SW cache version bumped for the new asset');
});
