'use strict';

// PR-F — structural wiring guards for the "Start this plan" acceptance button and
// its app.js bridge, read against the built shell (public/, regenerated by pretest).
// Complements the behavioral unit tests (planAcceptance.test.js / …Persistence):
// pins that the button exists on the plan card, is the ONLY acceptance trigger,
// posts ONLY /accept (no outcome/closeout in PR-F), never touches the main
// workout-write path, and leaves the generic "Start Session" control unchanged.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const publicDir = path.join(__dirname, '..', 'public');
const app = fs.readFileSync(path.join(publicDir, 'app.js'), 'utf8');
const cc = fs.readFileSync(path.join(publicDir, 'coach-conversation.js'), 'utf8');
const sw = fs.readFileSync(path.join(publicDir, 'sw.js'), 'utf8');

// The acceptDisplayedPlan function body (adapter) — sliced for scoped assertions.
const acceptBlock = app.slice(app.indexOf('async function acceptDisplayedPlan('), app.indexOf('function emitPlanItemOutcome('));

test('the "Start this plan" button is rendered on the plan card and refers to the displayed plan', () => {
  assert.match(cc, /function appendStartThisPlanButton\(container, rec\)/, 'the plan-card accept button helper exists');
  assert.match(cc, /'Start this plan'/, 'the button is labelled "Start this plan"');
  // It is appended right after the plan card is rendered (attached to the displayed plan).
  assert.match(cc, /appendWorkoutPlan\(body, rec\);\s*\n\s*appendStartThisPlanButton\(body, rec\);/,
    'the button is appended immediately after the rendered plan card, for the same rec');
});

test('the button is the ONLY acceptance trigger — acceptance runs only on an explicit click', () => {
  const btnBlock = cc.slice(cc.indexOf('function appendStartThisPlanButton('), cc.indexOf('function appendStartThisPlanButton(') + 1600);
  // atlasAcceptPlan is invoked ONLY inside the click handler — merely rendering the
  // card (Coach's Pick materialization) never accepts (owner tests 5 & 18).
  assert.match(btnBlock, /addEventListener\('click', async \(\) => \{[\s\S]*window\.atlasAcceptPlan\(rec\)/,
    'atlasAcceptPlan is called only from the button click handler');
  const beforeHandler = btnBlock.slice(0, btnBlock.indexOf("addEventListener('click'"));
  // The only pre-handler reference is the feature-detect guard (typeof …); acceptance
  // is never INVOKED before the click.
  assert.doesNotMatch(beforeHandler, /atlasAcceptPlan\(rec\)/, 'no acceptance is invoked at render time');
});

test('acceptDisplayedPlan is bridged and delegates to the pure orchestrator', () => {
  assert.match(app, /window\.atlasAcceptPlan = acceptDisplayedPlan;/, 'the adapter is bridged for the coach IIFE');
  assert.match(app, /import \{ runAcceptance \} from '\.\/planAcceptance\.js';/, 'app.js imports the pure orchestrator');
  assert.match(acceptBlock, /runAcceptance\(/, 'the adapter delegates to runAcceptance');
});

test('acceptance posts ONLY /api/session-plans/accept — no outcome or closeout in PR-F', () => {
  assert.match(acceptBlock, /\/api\/session-plans\/accept/, 'the adapter posts to the accept endpoint');
  // The ACCEPTANCE flow itself emits only /accept — never an outcome or closeout.
  // (PR-G1 adds /outcome elsewhere in app.js at the explicit skip/substitute handlers;
  // closeout stays unwired until PR-H.)
  assert.doesNotMatch(acceptBlock, /\/api\/session-plans\/outcome/, 'the accept flow does not send an outcome');
  assert.doesNotMatch(acceptBlock, /\/api\/session-plans\/closeout/, 'the accept flow does not send a closeout');
});

test('acceptance never touches the main workout-write / trust path', () => {
  assert.doesNotMatch(acceptBlock, /\/api\/log-workout|\/api\/complete-workout|sheet_write|no_write_confirmed|beginWrite/,
    'the acceptance adapter must not touch the workout write/proof path (sidecar only)');
});

test('the generic "Start Session" control is unchanged (still non-authoritative)', () => {
  // #start-session-btn still only opens the Coach\'s Pick surface — it is NOT wired to
  // acceptance (owner test 19). The distinct plan-card button owns acceptance.
  assert.match(app, /btn\.onclick = openCoachPickInThread;/, 'the generic Start Session button still just opens the coach surface');
  assert.doesNotMatch(app, /start-session-btn[\s\S]{0,200}atlasAcceptPlan/, 'the generic control is not repurposed for acceptance');
});

test('acceptance clears any stale pending swap (new-session boundary, parity with startPlannedSession)', () => {
  assert.match(acceptBlock, /setPendingSubstitution\(null\)/,
    'a newly-accepted session must not inherit a stale swap');
});

test('the "Start this plan" button is suppressed for a deload pick (deload stays owner-gated / out of scope)', () => {
  const btnBlock = cc.slice(cc.indexOf('function appendStartThisPlanButton('), cc.indexOf('function appendStartThisPlanButton(') + 1800);
  assert.match(btnBlock, /rec\.id === 'deload_reset'\) return;/, 'the acceptance button is not rendered for a deload pick');
});

test('the button is restored (never stuck on "Starting…") when a concurrent acceptance is ignored', () => {
  const btnBlock = cc.slice(cc.indexOf('function appendStartThisPlanButton('), cc.indexOf('function appendStartThisPlanButton(') + 1800);
  const ignoredBranch = btnBlock.slice(btnBlock.indexOf('result.ignored'), btnBlock.indexOf('} else {', btnBlock.indexOf('result.ignored')));
  assert.match(ignoredBranch, /btn\.disabled = false/, 'the ignored branch re-enables the button');
  assert.match(ignoredBranch, /btn\.textContent = original/, 'the ignored branch restores the label');
});

test('the new module is precached and the shell cache is bumped', () => {
  assert.match(sw, /\/app\/planAcceptance\.js/, 'planAcceptance.js is in SHELL_ASSETS (offline-safe)');
  assert.match(sw, /atlas-shell-v141/, 'the SW cache version is bumped for the new asset');
});
