'use strict';

/**
 * Training SME knowledge cards — structured, on-demand resistance-training reference material.
 *
 * These cards are the source of truth for Atlas's *educational* answers. They are deliberately
 * compact and structured (not essays) so answers are reliable and testable. Atlas assembles
 * answers from these fields; it does not invent claims. This layer changes NO recommendation
 * numbers and does not replace the rule engine (PR #209/#210).
 *
 * Card shape:
 *   id, title, shortAnswer, detailedAnswer, appliesToGoals, whenToUse, whenToAvoid,
 *   commonMistakes, atlasDecisionImpact, confidenceLevel, relatedTopics
 *   (+ matchTerms — internal retrieval keywords)
 *
 * `appliesToGoals` uses only canonical goal ids from trainingKnowledge.js.
 * `confidenceLevel` is one of: 'high' | 'moderate' | 'emerging' | 'context_dependent'.
 */

const CARDS = [
  {
    id: 'progressive_overload',
    title: 'Progressive Overload',
    shortAnswer: 'Do gradually more over time — load, reps, sets, or quality — so the body keeps adapting.',
    detailedAnswer: 'Overload is more than weight: you can add reps, add sets, add weekly volume, improve technique or range of motion, shorten rest, or raise effort. Change one lever at a time and only when recovery supports it. Logging is what makes real progression visible instead of guessed.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Any time you want measurable long-term progress', 'When recent sessions were completed with clean technique'],
    whenToAvoid: ['When fatigued, in pain, or under-recovered — hold or reduce instead'],
    commonMistakes: ['Adding load and volume and novelty all at once', 'Chasing soreness as if it were progress'],
    atlasDecisionImpact: 'Drives the engine’s add_load / add_rep / add_set / maintain decisions per goal.',
    confidenceLevel: 'high',
    relatedTopics: ['rep_ranges', 'training_volume', 'rir_rpe', 'plateaus'],
    matchTerms: ['progressive overload', 'overload', 'progress', 'how to progress', 'add weight'],
  },
  {
    id: 'strength_training',
    title: 'Strength Training',
    shortAnswer: 'Heavier loads, lower reps (~1–6), longer rest, progress mainly by adding load.',
    detailedAnswer: 'Strength prioritizes maximal force: lower reps, heavier loads, longer rest, main lifts first. Progress load when the top of the rep range is hit with target reps-in-reserve and clean form. Failure is generally avoided on heavy compounds because it costs recovery without much extra strength.',
    appliesToGoals: ['strength', 'mixed'],
    whenToUse: ['Goal is a bigger 1RM or heavier main lifts', 'Recovery is good and technique is solid'],
    whenToAvoid: ['When the goal is mainly size or work capacity'],
    commonMistakes: ['Turning strength days into high-fatigue pump circuits', 'Grinding ugly reps and calling it progress'],
    atlasDecisionImpact: 'Selects the strength policy: low rep range, heavy bias, load-first progression.',
    confidenceLevel: 'high',
    relatedTopics: ['hypertrophy_training', 'rep_ranges', 'training_to_failure', 'rest_periods'],
    matchTerms: ['strength', 'get stronger', 'max strength', '1rm', 'heavy', 'powerlifting'],
  },
  {
    id: 'hypertrophy_training',
    title: 'Hypertrophy Training',
    shortAnswer: 'Moderate reps (~8–15), enough hard weekly volume, add reps before load, train close to failure.',
    detailedAnswer: 'Muscle growth is driven by sufficient effort and recoverable weekly volume. Stay mostly in 8–15 reps (5–30 works with enough effort), add reps before load while inside the range, then add load once the top of the range is clean. Train close to failure — proximity to failure matters more here than for max strength.',
    appliesToGoals: ['hypertrophy', 'mixed', 'general_health'],
    whenToUse: ['Goal is size or building a specific muscle', 'You can recover from moderate-to-high volume'],
    whenToAvoid: ['When the priority is a max single or pure speed'],
    commonMistakes: ['Adding load every session and leaving the rep range', 'Junk volume with no progression'],
    atlasDecisionImpact: 'Selects the hypertrophy policy: rep-before-load progression, volume bias.',
    confidenceLevel: 'high',
    relatedTopics: ['strength_training', 'training_volume', 'training_to_failure', 'rep_ranges'],
    matchTerms: ['hypertrophy', 'muscle', 'build muscle', 'size', 'bodybuilding', 'grow'],
  },
  {
    id: 'muscular_endurance',
    title: 'Muscular Endurance',
    shortAnswer: 'Higher reps (~15–25+), shorter rest, progress density and reps before load.',
    detailedAnswer: 'Muscular endurance is a muscle’s ability to sustain repeated contractions. It uses higher reps and shorter rest, and progresses by doing more work in less time (density) and adding reps before load. It is distinct from cardio/running endurance and from fat-loss conditioning.',
    appliesToGoals: ['muscular_endurance', 'conditioning_fat_loss', 'general_health'],
    whenToUse: ['Goal is high-rep stamina in the muscle', 'Sport or work needs repeated submaximal effort'],
    whenToAvoid: ['When the goal is a max single or maximal hypertrophy stimulus per set'],
    commonMistakes: ['Confusing it with running/cardio endurance', 'Going so light there is no real effort'],
    atlasDecisionImpact: 'Selects the muscular_endurance policy: high reps, short rest, density-first.',
    confidenceLevel: 'high',
    relatedTopics: ['rep_ranges', 'rest_periods', 'training_volume'],
    matchTerms: ['muscular endurance', 'endurance', 'high reps', 'stamina', 'rep endurance'],
  },
  {
    id: 'power_training',
    title: 'Power Training',
    shortAnswer: 'Low reps, moderate load, high reps-in-reserve, move fast — never grind to failure.',
    detailedAnswer: 'Power is force produced quickly. Keep reps low (1–5), load moderate (~30–70% 1RM where it applies), and rest enough to keep bar speed crisp. Stop the set when speed drops. Grindy reps and training to failure are wrong for power — they build fatigue, not explosiveness.',
    appliesToGoals: ['power', 'mixed'],
    whenToUse: ['Goal is explosiveness, jump/throw, or athletic speed', 'You are fresh and warmed up'],
    whenToAvoid: ['When fatigued or when reps are already slowing'],
    commonMistakes: ['Grinding slow reps', 'Adding so much load that speed collapses'],
    atlasDecisionImpact: 'Selects the power policy: high RIR, speed protection, no failure prescription.',
    confidenceLevel: 'high',
    relatedTopics: ['strength_training', 'training_to_failure', 'rir_rpe'],
    matchTerms: ['power', 'explosive', 'speed', 'velocity', 'jump', 'athletic'],
  },
  {
    id: 'powerbuilding',
    title: 'Powerbuilding (Mixed)',
    shortAnswer: 'Strength-biased main lift, hypertrophy-biased accessories, fatigue controls stay on.',
    detailedAnswer: 'Powerbuilding blends strength and size: drive measurable strength on the main lift (lower reps, load-first), then build volume with hypertrophy-style accessories (8–15 reps, rep-first). Keep fatigue management active so neither goal trashes the other. A good default when no single goal dominates.',
    appliesToGoals: ['mixed', 'strength', 'hypertrophy'],
    whenToUse: ['You want strength and size together', 'No single goal clearly dominates'],
    whenToAvoid: ['When you specifically need a peak in only one quality'],
    commonMistakes: ['Treating accessories as heavy strength work', 'Letting accessory volume wreck main-lift recovery'],
    atlasDecisionImpact: 'Selects the mixed policy: strength main lift + hypertrophy accessories.',
    confidenceLevel: 'high',
    relatedTopics: ['strength_training', 'hypertrophy_training', 'program_splits'],
    matchTerms: ['powerbuilding', 'strength and size', 'mixed', 'powerbuild'],
  },
  {
    id: 'training_to_failure',
    title: 'Training to Failure',
    shortAnswer: 'Not required for strength or size; proximity to failure matters more for hypertrophy than max strength.',
    detailedAnswer: 'Going to failure is not required to build strength or muscle. Training close to failure matters more for hypertrophy than for maximal strength, where leaving 1–3 reps in reserve protects technique and recovery. Save occasional true failure for safer isolation/machine work, not heavy compounds — and never for power.',
    appliesToGoals: ['strength', 'hypertrophy', 'muscular_endurance', 'power', 'mixed'],
    whenToUse: ['Late isolation sets where failure is safe', 'Calibrating how hard a set really was'],
    whenToAvoid: ['Heavy compounds, power work, fatigued or under-recovered states'],
    commonMistakes: ['Going to failure every set', 'Equating exhaustion with effectiveness'],
    atlasDecisionImpact: 'Informs per-goal failurePolicy and RIR targets in the rule engine.',
    confidenceLevel: 'high',
    relatedTopics: ['rir_rpe', 'hypertrophy_training', 'power_training'],
    matchTerms: ['training to failure', 'to failure', 'failure', 'amrap', 'all out'],
  },
  {
    id: 'rir_rpe',
    title: 'RIR / RPE',
    shortAnswer: 'RIR = reps in reserve; RPE = rated effort. They calibrate how close to failure a set was.',
    detailedAnswer: 'RIR is how many clean reps you had left; RPE is the inverse rated effort (RPE 8 ≈ 2 RIR). Use them honestly to autoregulate: if a set was harder than planned (lower RIR), ease off; if easier with solid technique (higher RIR), you can add a little. Strength keeps 1–3 RIR; power stays well short of failure.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Logging effort honestly', 'Deciding next-set or next-session load'],
    whenToAvoid: ['As an excuse to grind — RIR 0 every set is not the goal'],
    commonMistakes: ['Overrating RIR (claiming more in reserve than there was)', 'Ignoring technique breakdown'],
    atlasDecisionImpact: 'Feeds autoregulation and progression triggers across goals.',
    confidenceLevel: 'high',
    relatedTopics: ['training_to_failure', 'progressive_overload'],
    matchTerms: ['rir', 'rpe', 'reps in reserve', 'rate of perceived exertion', 'effort'],
  },
  {
    id: 'deloads',
    title: 'Deloads',
    shortAnswer: 'A planned easier block: reduce load, volume, or exercise stress to shed fatigue — not every tired day.',
    detailedAnswer: 'A deload is a deliberate reduction in load, volume, or overall exercise stress to let fatigue drop while keeping the movement habit. It is not the right label for every tired day — a single low day is just a reduced-stress session. Use a true deload when performance stalls, joints ache, or systemic fatigue accumulates.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed', 'recovery'],
    whenToUse: ['Performance dropping, persistent fatigue, achy joints', 'After a long hard block'],
    whenToAvoid: ['Calling every easier day a dramatic “deload & reset”'],
    commonMistakes: ['Deloading nothing (token reduction)', 'Mislabeling one tired day as a deload'],
    atlasDecisionImpact: 'Maps to recovery policy and reduce-stress adjustments, not dramatic default labels.',
    confidenceLevel: 'high',
    relatedTopics: ['training_volume', 'pain_vs_soreness', 'plateaus'],
    matchTerms: ['deload', 'deloads', 'reset week', 'recovery week', 'back off week'],
  },
  {
    id: 'warmups_ramp_sets',
    title: 'Warm-ups & Ramp Sets',
    shortAnswer: 'A short general warm-up plus a few ramp sets to your top weight — not extra fatigue.',
    detailedAnswer: 'Warm up enough to move well and rehearse the pattern: a brief general warm-up, then a few progressively heavier ramp sets toward the working load. Heavier days need more ramp sets; lighter, high-rep work needs fewer. Warm-ups prime performance; they should not pre-fatigue the working sets.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Before heavy or technical lifts', 'When cold or first exercise of the day'],
    whenToAvoid: ['Doing so many warm-up sets they eat into working capacity'],
    commonMistakes: ['Jumping straight to a heavy top set', 'Burning energy on excessive warm-up volume'],
    atlasDecisionImpact: 'Context for session structure; does not change prescribed working numbers.',
    confidenceLevel: 'moderate',
    relatedTopics: ['power_training', 'strength_training'],
    matchTerms: ['warm up', 'warmup', 'warm-up', 'ramp sets', 'ramp up', 'priming'],
  },
  {
    id: 'rest_periods',
    title: 'Rest Periods',
    shortAnswer: 'Rest long enough to keep quality: longer for strength/power, shorter for endurance/density.',
    detailedAnswer: 'Rest enough to keep the next set’s quality high. Heavy strength and power want longer rests (~2–4 min) to preserve force and speed; hypertrophy is fine around 1.5–3 min; endurance and density work use shorter rests on purpose. Cutting rest is a real progression lever — but not at the cost of main-lift quality.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'conditioning_fat_loss', 'mixed'],
    whenToUse: ['Setting pace between sets', 'Trading density vs load quality'],
    whenToAvoid: ['Rushing heavy strength/power sets and losing output'],
    commonMistakes: ['Resting too little on heavy work', 'Resting randomly with no intent'],
    atlasDecisionImpact: 'Aligns with each goal’s restSeconds target band.',
    confidenceLevel: 'high',
    relatedTopics: ['rep_ranges', 'muscular_endurance', 'power_training'],
    matchTerms: ['rest period', 'rest periods', 'rest time', 'how long to rest', 'rest between sets'],
  },
  {
    id: 'rep_ranges',
    title: 'Rep Ranges',
    shortAnswer: 'Lower reps bias strength, moderate reps bias size, higher reps bias endurance — with overlap.',
    detailedAnswer: 'Rep ranges are biases, not hard walls. ~1–6 leans strength, ~6–15 leans hypertrophy, ~15+ leans muscular endurance, and power stays low with high speed. Effort and proximity to failure matter as much as the number. Pick a range that fits the goal, then progress inside it before changing load.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Choosing how a set should feel for a goal', 'Deciding when to add load vs reps'],
    whenToAvoid: ['Treating ranges as rigid or magic numbers'],
    commonMistakes: ['Always 3x10 regardless of goal', 'Ignoring effort and only watching the rep number'],
    atlasDecisionImpact: 'Maps directly to each goal’s preferred/allowed rep ranges.',
    confidenceLevel: 'high',
    relatedTopics: ['strength_training', 'hypertrophy_training', 'muscular_endurance'],
    matchTerms: ['rep range', 'rep ranges', 'how many reps', 'reps for', 'sets and reps'],
  },
  {
    id: 'training_volume',
    title: 'Training Volume',
    shortAnswer: 'Hard weekly sets per muscle drive growth — enough to progress, not more than you recover from.',
    detailedAnswer: 'Volume (roughly hard sets per muscle per week) is a primary growth driver. Do enough to progress and add volume only when recovery is good; more is not always better once it outpaces recovery. Track it across the week, not just per session, and back off when performance or sleep degrades.',
    appliesToGoals: ['hypertrophy', 'strength', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Planning weekly work per muscle', 'Diagnosing too-little or too-much training'],
    whenToAvoid: ['Adding volume while under-recovered'],
    commonMistakes: ['Junk volume with no progression', 'Massive jumps in weekly sets'],
    atlasDecisionImpact: 'Informs add_set decisions and weekly set targets per goal.',
    confidenceLevel: 'high',
    relatedTopics: ['training_frequency', 'deloads', 'progressive_overload'],
    matchTerms: ['volume', 'how many sets', 'weekly sets', 'sets per muscle', 'too much volume'],
  },
  {
    id: 'training_frequency',
    title: 'Training Frequency',
    shortAnswer: 'How often you train a muscle/pattern per week — spread volume to support recovery and quality.',
    detailedAnswer: 'Frequency is how often a muscle or movement is trained weekly. Spreading weekly volume across more sessions can improve quality and recovery per session, but total volume and recovery matter more than frequency itself. Fit frequency to schedule, recovery, and how the volume is distributed.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Designing a weekly split', 'Distributing volume across days'],
    whenToAvoid: ['Cramming all volume into one brutal session if it hurts quality'],
    commonMistakes: ['Assuming more frequency always beats more total volume', 'Ignoring recovery between same-pattern days'],
    atlasDecisionImpact: 'Context for split/recovery; constraint trainingDaysPerWeek can bias compounds.',
    confidenceLevel: 'moderate',
    relatedTopics: ['program_splits', 'training_volume', 'deloads'],
    matchTerms: ['frequency', 'how often', 'times per week', 'training frequency', 'days per week'],
  },
  {
    id: 'compound_vs_isolation',
    title: 'Compound vs Isolation',
    shortAnswer: 'Compounds build the most strength/size per set; isolations target weak points and add safe volume.',
    detailedAnswer: 'Compound lifts (squat, bench, row, press) move the most load across multiple joints and give the best strength and size return per set, so they usually go first. Isolation work targets specific muscles, adds recoverable volume, and is a safer place for near-failure sets. Most programs use both.',
    appliesToGoals: ['strength', 'hypertrophy', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Ordering a session (compounds first)', 'Bringing up a lagging muscle with isolation'],
    whenToAvoid: ['Replacing all compounds with isolation when strength is the goal'],
    commonMistakes: ['Skipping compounds', 'Only doing compounds and never addressing weak points'],
    atlasDecisionImpact: 'Mirrors exercise-order rules and accessory progression in the mixed policy.',
    confidenceLevel: 'high',
    relatedTopics: ['machines_vs_free_weights', 'exercise_substitution', 'program_splits'],
    matchTerms: ['compound', 'isolation', 'compound vs isolation', 'accessory', 'big lifts'],
  },
  {
    id: 'machines_vs_free_weights',
    title: 'Machines vs Free Weights',
    shortAnswer: 'Both build muscle; free weights teach skill/stability, machines add stable, low-skill volume.',
    detailedAnswer: 'For hypertrophy, machines and free weights both work well — pick by stimulus, joint comfort, and what you can progress and recover from. Free weights demand more stability and skill (useful for strength and athletic carryover); machines let you push close to failure safely and add volume with less technical fatigue.',
    appliesToGoals: ['hypertrophy', 'strength', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Choosing a tool for a muscle', 'Working around skill, fatigue, or joint issues'],
    whenToAvoid: ['Believing one category is universally superior'],
    commonMistakes: ['Dismissing machines as “not real training”', 'Forcing a painful free-weight lift on principle'],
    atlasDecisionImpact: 'Supports exercise-type handling and equipmentTier constraint.',
    confidenceLevel: 'high',
    relatedTopics: ['compound_vs_isolation', 'exercise_substitution'],
    matchTerms: ['machines', 'free weights', 'machine vs free weight', 'dumbbells vs machine', 'smith machine'],
  },
  {
    id: 'exercise_substitution',
    title: 'Exercise Substitution',
    shortAnswer: 'Swap for the same target muscle/pattern and similar stimulus — keep the job, change the tool.',
    detailedAnswer: 'When an exercise causes pain, isn’t available, or stalls, substitute one that trains the same muscle or movement pattern with a similar stimulus and rep range. Keep the training job the same; change the tool. Don’t program-hop randomly — substitute with intent and then progress the new choice.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed', 'recovery'],
    whenToUse: ['Pain, equipment limits, or a persistent stall', 'Adapting to a constraint'],
    whenToAvoid: ['Swapping constantly so nothing gets progressed'],
    commonMistakes: ['Random program hopping', 'Substituting a totally different stimulus'],
    atlasDecisionImpact: 'Supports painFlags/equipment constraints and change-exercise adjustments.',
    confidenceLevel: 'moderate',
    relatedTopics: ['machines_vs_free_weights', 'pain_vs_soreness', 'plateaus'],
    matchTerms: ['substitution', 'substitute', 'swap exercise', 'replace exercise', 'alternative exercise'],
  },
  {
    id: 'plateaus',
    title: 'Plateaus',
    shortAnswer: 'Stalls usually mean recovery, technique, or progression-lever problems — not “work harder.”',
    detailedAnswer: 'A plateau is several sessions with no improvement. Before forcing more, check the usual causes: under-recovery (sleep, stress, fatigue), technique or range-of-motion drift, too little or too much volume, or always pushing the same lever. Fixes include a small deload, a technique reset, adjusting volume, or changing the progression lever — not just adding weight.',
    appliesToGoals: ['strength', 'hypertrophy', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['When a lift stops improving for several sessions'],
    whenToAvoid: ['Reacting to one off day as a plateau'],
    commonMistakes: ['Adding load into a stall', 'Ignoring recovery and technique'],
    atlasDecisionImpact: 'Aligns with stall detection and maintain/reduce-stress decisions.',
    confidenceLevel: 'high',
    relatedTopics: ['deloads', 'progressive_overload', 'training_volume'],
    matchTerms: ['plateau', 'plateaus', 'stall', 'stalled', 'stuck', 'not progressing'],
  },
  {
    id: 'pain_vs_soreness',
    title: 'Pain vs Soreness',
    shortAnswer: 'Normal muscle soreness is dull and fades; sharp, joint, or worsening pain means back off — not a diagnosis.',
    detailedAnswer: 'Typical muscle soreness (DOMS) is dull, spread across the muscle, and eases within a few days; it is not required for a workout to be effective. Sharp, joint-centered, one-sided, or worsening pain is a warning sign — reduce load or range, or change the exercise. This is general guidance, not a medical diagnosis: if pain is sharp, severe, persistent, or worsening, stop and consult a qualified professional.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed', 'recovery'],
    whenToUse: ['Deciding whether to train through a sensation', 'Distinguishing soreness from injury risk'],
    whenToAvoid: ['Pushing through sharp or worsening pain', 'Using soreness as a measure of a good session'],
    commonMistakes: ['Training through joint pain', 'Chasing soreness as the goal'],
    atlasDecisionImpact: 'Pain flags trigger regress/hold and never push load into pain.',
    confidenceLevel: 'context_dependent',
    relatedTopics: ['exercise_substitution', 'deloads', 'rir_rpe'],
    matchTerms: ['pain', 'soreness', 'sore', 'doms', 'pain vs soreness', 'joint pain', 'hurts'],
  },
  {
    id: 'program_splits',
    title: 'Program Splits',
    shortAnswer: 'Full-body, upper/lower, or push/pull/legs — pick by days available and recovery, then progress it.',
    detailedAnswer: 'A split organizes weekly volume: full-body suits 2–3 days, upper/lower suits 3–4, push/pull/legs suits 4–6. No split is magic — what matters is hitting enough weekly volume per muscle with adequate recovery and actually progressing it. Match the split to your schedule and recovery, then stay consistent.',
    appliesToGoals: ['strength', 'hypertrophy', 'power', 'muscular_endurance', 'general_health', 'mixed'],
    whenToUse: ['Designing a week of training', 'Matching training to available days'],
    whenToAvoid: ['Switching splits constantly instead of progressing one'],
    commonMistakes: ['Copying an advanced split with too few recovery days', 'Program hopping'],
    atlasDecisionImpact: 'Context for weekly structure; does not change prescribed numbers.',
    confidenceLevel: 'high',
    relatedTopics: ['training_frequency', 'training_volume', 'compound_vs_isolation'],
    matchTerms: ['split', 'splits', 'program split', 'ppl', 'push pull legs', 'upper lower', 'full body'],
  },
];

const CARDS_BY_ID = CARDS.reduce((acc, card) => {
  acc[card.id] = card;
  return acc;
}, {});

function getCardById(id) {
  return CARDS_BY_ID[id] || null;
}

function allCardIds() {
  return CARDS.map((c) => c.id);
}

module.exports = {
  CARDS,
  CARDS_BY_ID,
  getCardById,
  allCardIds,
};
