const routeDefinitions = [
  { path: '/', methods: ['GET'], public: true, authRequired: false, readOnly: true, writeCapable: false },
  { path: '/health', methods: ['GET'], public: true, authRequired: false, readOnly: true, writeCapable: false },
  { path: '/routes', methods: ['GET'], public: true, authRequired: false, readOnly: true, writeCapable: false },
  { path: '/version', methods: ['GET'], public: true, authRequired: false, readOnly: true, writeCapable: false },
  { path: '/app', methods: ['GET'], public: true, authRequired: false, readOnly: true, writeCapable: false },
  { path: '/api/history/recent', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/exercises/last-session', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/exercises/:liftCode', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/recommend/next/:liftCode', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/progress/summary', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/summary/weekly', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/prs/recent', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/pending-exercises', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/sessions/recent', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/sessions/:sessionId', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/session/:sessionId', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/catalog/exercises', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/catalog/search', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/health/sheets', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/health/openai', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/debug/config', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/debug/exercise-match', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/schema/log', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/schema/effort', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/schema/complete-workout', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/plan/today', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/plan/intent-recommendation', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/parse-workout-text', methods: ['POST'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/parse-workout-image', methods: ['POST'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/complete-workout', methods: ['POST'], public: false, authRequired: true, readOnly: false, writeCapable: true },
  { path: '/api/log-workout', methods: ['POST'], public: false, authRequired: true, readOnly: false, writeCapable: true },
  { path: '/api/log-workout/undo-last', methods: ['POST'], public: false, authRequired: true, readOnly: false, writeCapable: true },
  { path: '/api/log-workout/verify-range', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/session/:sessionId/summary', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/exercises/:liftCode/progress', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/exercises/:liftCode/detail', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/volume/muscle-groups', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/search/sessions', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/bodyweight', methods: ['POST'], public: false, authRequired: true, readOnly: false, writeCapable: true },
  { path: '/api/bodyweight/history', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/admin/preview-test-rows', methods: ['POST'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/stalls', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/report/weekly', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false },
  { path: '/api/coaching/insights', methods: ['GET'], public: false, authRequired: true, readOnly: true, writeCapable: false }
];

module.exports = { routeDefinitions };
